import type { Job, Scope } from "./types";

/**
 * Hand-authored fixture jobs standing in for what a real connector (Airflow,
 * Dagster, Temporal, ...) would report. Seven team scopes on purpose: four
 * are "ordinary" teams carrying the recovering/late/missing/critical
 * scenarios, one (support-ops) is deliberately quiet so the plain "healthy"
 * headline is always demonstrable too, and two (ml-platform, quarterly-ops)
 * exist specifically to make the "no data yet" and "nothing scheduled in
 * this window" edge cases reliably demonstrable rather than luck-of-the-draw.
 */

export const SCOPES: Scope[] = [
  { id: "all", name: "All", kind: "all" },
  { id: "data-platform", name: "Data Platform", kind: "team" },
  { id: "payments", name: "Payments", kind: "team" },
  { id: "growth", name: "Growth", kind: "team" },
  { id: "infrastructure", name: "Infrastructure", kind: "team" },
  { id: "support-ops", name: "Support Ops", kind: "team" },
  { id: "ml-platform", name: "ML Platform", kind: "team" },
  { id: "quarterly-ops", name: "Quarterly Ops", kind: "team" },
];

const sla = (expectedDurationMinutes: number, graceMinutes = 20) => ({
  expectedDurationMinutes,
  graceMinutes,
});

export const JOBS: Job[] = [
  // ---- Data Platform: hosts the "critical + blocks downstream" scenario ----
  {
    id: "ingest-events-raw",
    name: "Ingest raw events",
    owner: "Data Platform",
    scopeId: "data-platform",
    schedule: { cadence: "hourly" },
    sla: sla(10),
    dependsOn: [],
  },
  {
    id: "ingest-payments-raw",
    name: "Ingest raw payments",
    owner: "Data Platform",
    scopeId: "data-platform",
    schedule: { cadence: "hourly" },
    sla: sla(10),
    dependsOn: [],
  },
  {
    id: "clean-events",
    name: "Clean events",
    owner: "Data Platform",
    scopeId: "data-platform",
    schedule: { cadence: "hourly" },
    sla: sla(15),
    dependsOn: ["ingest-events-raw"],
  },
  {
    id: "dedupe-payments",
    name: "Dedupe payments",
    owner: "Data Platform",
    scopeId: "data-platform",
    schedule: { cadence: "hourly" },
    sla: sla(15),
    dependsOn: ["ingest-payments-raw"],
  },
  {
    id: "build-user-sessions",
    name: "Build user sessions",
    owner: "Data Platform",
    scopeId: "data-platform",
    schedule: { cadence: "daily", hour: 2, minute: 0 },
    sla: sla(45),
    dependsOn: ["clean-events"],
  },
  {
    id: "build-revenue-facts",
    name: "Build revenue facts",
    owner: "Data Platform",
    scopeId: "data-platform",
    schedule: { cadence: "daily", hour: 3, minute: 0 },
    sla: sla(40, 30),
    dependsOn: ["dedupe-payments"],
  },
  {
    id: "daily-exec-dashboard-refresh",
    name: "Daily exec dashboard refresh",
    owner: "Data Platform",
    scopeId: "data-platform",
    schedule: { cadence: "daily", hour: 6, minute: 0 },
    sla: sla(20),
    dependsOn: ["build-user-sessions", "build-revenue-facts"],
  },
  {
    id: "weekly-finance-rollup",
    name: "Weekly finance rollup",
    owner: "Data Platform",
    scopeId: "data-platform",
    schedule: { cadence: "weekly", weekday: 1, hour: 7, minute: 0 },
    sla: sla(60),
    dependsOn: ["build-revenue-facts"],
  },
  {
    id: "warehouse-vacuum",
    name: "Warehouse vacuum",
    owner: "Data Platform",
    scopeId: "data-platform",
    schedule: { cadence: "daily", hour: 1, minute: 0 },
    sla: sla(30),
    dependsOn: [],
  },
  {
    id: "schema-drift-check",
    name: "Schema drift check",
    owner: "Data Platform",
    scopeId: "data-platform",
    schedule: { cadence: "every_6_hours" },
    sla: sla(10),
    dependsOn: [],
  },

  // ---- Payments: hosts the "recovering" scenario ----
  {
    id: "capture-transactions",
    name: "Capture transactions",
    owner: "Payments",
    scopeId: "payments",
    schedule: { cadence: "hourly" },
    sla: sla(10),
    dependsOn: [],
  },
  {
    id: "reconcile-ledger",
    name: "Reconcile ledger",
    owner: "Payments",
    scopeId: "payments",
    schedule: { cadence: "hourly" },
    sla: sla(15),
    dependsOn: ["capture-transactions"],
  },
  {
    id: "detect-fraud-signals",
    name: "Detect fraud signals",
    owner: "Payments",
    scopeId: "payments",
    schedule: { cadence: "hourly" },
    sla: sla(10),
    dependsOn: ["capture-transactions"],
  },
  {
    id: "chargeback-sync",
    name: "Chargeback sync",
    owner: "Payments",
    scopeId: "payments",
    schedule: { cadence: "hourly" },
    sla: sla(10),
    dependsOn: [],
  },
  {
    id: "settle-daily-batch",
    name: "Settle daily batch",
    owner: "Payments",
    scopeId: "payments",
    schedule: { cadence: "daily", hour: 22, minute: 0 },
    sla: sla(50),
    dependsOn: ["reconcile-ledger"],
  },
  {
    id: "refund-processor",
    name: "Refund processor",
    owner: "Payments",
    scopeId: "payments",
    schedule: { cadence: "daily", hour: 5, minute: 0 },
    sla: sla(20),
    dependsOn: [],
  },
  {
    id: "payment-method-vault-sync",
    name: "Payment method vault sync",
    owner: "Payments",
    scopeId: "payments",
    schedule: { cadence: "daily", hour: 4, minute: 0 },
    sla: sla(15),
    dependsOn: [],
  },
  {
    id: "tax-calc-batch",
    name: "Tax calc batch",
    owner: "Payments",
    scopeId: "payments",
    schedule: { cadence: "daily", hour: 5, minute: 30 },
    sla: sla(25),
    dependsOn: [],
  },
  {
    id: "payout-scheduler",
    name: "Payout scheduler",
    owner: "Payments",
    scopeId: "payments",
    schedule: { cadence: "daily", hour: 8, minute: 0 },
    sla: sla(20),
    dependsOn: [],
  },

  // ---- Growth: hosts the "missing" and "late" scenarios ----
  {
    id: "ingest-marketing-events",
    name: "Ingest marketing events",
    owner: "Growth",
    scopeId: "growth",
    schedule: { cadence: "hourly" },
    sla: sla(10),
    dependsOn: [],
  },
  {
    id: "attribution-model-run",
    name: "Attribution model run",
    owner: "Growth",
    scopeId: "growth",
    schedule: { cadence: "daily", hour: 4, minute: 0 },
    sla: sla(30, 20),
    dependsOn: ["ingest-marketing-events"],
  },
  {
    id: "campaign-spend-sync",
    name: "Campaign spend sync",
    owner: "Growth",
    scopeId: "growth",
    schedule: { cadence: "hourly" },
    sla: sla(10),
    dependsOn: [],
  },
  {
    id: "lead-scoring-batch",
    name: "Lead scoring batch",
    owner: "Growth",
    scopeId: "growth",
    schedule: { cadence: "daily", hour: 5, minute: 0 },
    sla: sla(25, 20),
    dependsOn: [],
  },
  {
    id: "email-engagement-rollup",
    name: "Email engagement rollup",
    owner: "Growth",
    scopeId: "growth",
    schedule: { cadence: "daily", hour: 6, minute: 0 },
    sla: sla(20),
    dependsOn: [],
  },
  {
    id: "seo-crawl-batch",
    name: "SEO crawl batch",
    owner: "Growth",
    scopeId: "growth",
    schedule: { cadence: "daily", hour: 3, minute: 0 },
    sla: sla(40),
    dependsOn: [],
  },
  {
    id: "churn-model-refresh",
    name: "Churn model refresh",
    owner: "Growth",
    scopeId: "growth",
    schedule: { cadence: "weekly", weekday: 3, hour: 6, minute: 0 },
    sla: sla(50),
    dependsOn: [],
  },
  {
    id: "ab-test-results-sync",
    name: "A/B test results sync",
    owner: "Growth",
    scopeId: "growth",
    schedule: { cadence: "hourly" },
    sla: sla(10),
    dependsOn: [],
  },
  {
    id: "referral-program-sync",
    name: "Referral program sync",
    owner: "Growth",
    scopeId: "growth",
    schedule: { cadence: "daily", hour: 7, minute: 0 },
    sla: sla(15),
    dependsOn: [],
  },

  // ---- Infrastructure: connector for this whole scope goes unreachable ----
  {
    id: "backup-verification",
    name: "Backup verification",
    owner: "Infrastructure",
    scopeId: "infrastructure",
    schedule: { cadence: "daily", hour: 2, minute: 0 },
    sla: sla(30),
    dependsOn: [],
  },
  {
    id: "certificate-rotation-check",
    name: "Certificate rotation check",
    owner: "Infrastructure",
    scopeId: "infrastructure",
    schedule: { cadence: "daily", hour: 3, minute: 0 },
    sla: sla(10),
    dependsOn: [],
  },
  {
    id: "cost-anomaly-scan",
    name: "Cost anomaly scan",
    owner: "Infrastructure",
    scopeId: "infrastructure",
    schedule: { cadence: "daily", hour: 4, minute: 0 },
    sla: sla(15),
    dependsOn: [],
  },
  {
    id: "capacity-forecast",
    name: "Capacity forecast",
    owner: "Infrastructure",
    scopeId: "infrastructure",
    schedule: { cadence: "weekly", weekday: 2, hour: 5, minute: 0 },
    sla: sla(45),
    dependsOn: [],
  },
  {
    id: "log-retention-cleanup",
    name: "Log retention cleanup",
    owner: "Infrastructure",
    scopeId: "infrastructure",
    schedule: { cadence: "daily", hour: 1, minute: 30 },
    sla: sla(20),
    dependsOn: [],
  },
  {
    id: "secrets-rotation",
    name: "Secrets rotation",
    owner: "Infrastructure",
    scopeId: "infrastructure",
    schedule: { cadence: "weekly", weekday: 5, hour: 6, minute: 0 },
    sla: sla(15),
    dependsOn: [],
  },
  {
    id: "node-health-sweep",
    name: "Node health sweep",
    owner: "Infrastructure",
    scopeId: "infrastructure",
    schedule: { cadence: "every_6_hours" },
    sla: sla(10),
    dependsOn: [],
  },
  {
    id: "dns-config-audit",
    name: "DNS config audit",
    owner: "Infrastructure",
    scopeId: "infrastructure",
    schedule: { cadence: "daily", hour: 5, minute: 0 },
    sla: sla(10),
    dependsOn: [],
  },

  // ---- Support Ops: deliberately quiet, demonstrates plain "healthy" ----
  {
    id: "ticket-sla-sync",
    name: "Ticket SLA sync",
    owner: "Support Ops",
    scopeId: "support-ops",
    schedule: { cadence: "hourly" },
    sla: sla(10),
    dependsOn: [],
  },
  {
    id: "kb-reindex",
    name: "Knowledge base reindex",
    owner: "Support Ops",
    scopeId: "support-ops",
    schedule: { cadence: "daily", hour: 2, minute: 30 },
    sla: sla(20),
    dependsOn: [],
  },
  {
    id: "csat-rollup",
    name: "CSAT rollup",
    owner: "Support Ops",
    scopeId: "support-ops",
    schedule: { cadence: "daily", hour: 6, minute: 0 },
    sla: sla(15),
    dependsOn: [],
  },
  {
    id: "escalation-digest",
    name: "Escalation digest",
    owner: "Support Ops",
    scopeId: "support-ops",
    schedule: { cadence: "daily", hour: 7, minute: 0 },
    sla: sla(10),
    dependsOn: [],
  },

  // ---- ML Platform: newly connected, no run history at all ----
  {
    id: "feature-store-sync",
    name: "Feature store sync",
    owner: "ML Platform",
    scopeId: "ml-platform",
    schedule: { cadence: "hourly" },
    sla: sla(10),
    dependsOn: [],
  },
  {
    id: "model-training-pipeline",
    name: "Model training pipeline",
    owner: "ML Platform",
    scopeId: "ml-platform",
    schedule: { cadence: "daily", hour: 2, minute: 0 },
    sla: sla(90),
    dependsOn: [],
  },
  {
    id: "inference-batch-scoring",
    name: "Inference batch scoring",
    owner: "ML Platform",
    scopeId: "ml-platform",
    schedule: { cadence: "hourly" },
    sla: sla(15),
    dependsOn: [],
  },

  // ---- Quarterly Ops: monthly cadence, essentially never due "today" ----
  {
    id: "quarterly-tax-filing-prep",
    name: "Quarterly tax filing prep",
    owner: "Finance Ops",
    scopeId: "quarterly-ops",
    schedule: { cadence: "monthly", dayOfMonth: 1, hour: 6, minute: 0 },
    sla: sla(60),
    dependsOn: [],
  },
  {
    id: "board-report-package",
    name: "Board report package",
    owner: "Finance Ops",
    scopeId: "quarterly-ops",
    schedule: { cadence: "monthly", dayOfMonth: 1, hour: 8, minute: 0 },
    sla: sla(45),
    dependsOn: [],
  },
  {
    id: "vendor-contract-audit",
    name: "Vendor contract audit",
    owner: "Finance Ops",
    scopeId: "quarterly-ops",
    schedule: { cadence: "monthly", dayOfMonth: 15, hour: 6, minute: 0 },
    sla: sla(60),
    dependsOn: [],
  },
];

export const JOBS_BY_SCOPE: Record<string, Job[]> = JOBS.reduce(
  (acc, job) => {
    (acc[job.scopeId] ??= []).push(job);
    return acc;
  },
  {} as Record<string, Job[]>,
);
